//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CascadingDropdownlist.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public int StudentId { get; set; }

        [Display(Name = "Full Name:")]
        [Required(ErrorMessage = "Full Name is required.")]
        public string FullName { get; set; }

        [Display(Name = "Email:")]
        [Required(ErrorMessage = "Email is required.")]
        public string Email { get; set; }

        [Display(Name = "Address:")]
        public string Address { get; set; }

        [Display(Name = "City:")]
        [Required(ErrorMessage = "City is required.")]
        [UIHint("CityDDL")]
        public Nullable<int> City { get; set; }

        [Display(Name = "State:")]
        [Required(ErrorMessage = "State is required.")]
        [UIHint("StateDDL")]
        public Nullable<int> State { get; set; }

        [Display(Name = "Country:")]
        [Required(ErrorMessage = "Country is required.")]
        [UIHint("CountryDDL")]
        public Nullable<int> Contry { get; set; }
    }
}
